# Generated by Django 4.0.5 on 2022-06-17 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='historicalsource',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='HistoricalCompany',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fullname', models.CharField(db_index=True, max_length=100)),
                ('shortname', models.CharField(db_index=True, max_length=20)),
                ('sn', models.CharField(db_index=True, max_length=9)),
                ('stock_id', models.CharField(blank=True, db_index=True, max_length=6, null=True)),
                ('addr_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_title', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_tel', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True)),
                ('report', models.TextField(blank=True, max_length=100, null=True)),
                ('pwr_usage', models.DecimalField(blank=True, decimal_places=1, max_digits=11, null=True)),
                ('pwr_inquire', models.DecimalField(blank=True, decimal_places=1, max_digits=11, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.IntegerField(default=0)),
                ('warn_date', models.DateField()),
                ('remark', models.CharField(blank=True, max_length=1000, null=True)),
                ('add_time', models.DateTimeField(blank=True, editable=False)),
                ('update_time', models.DateTimeField(blank=True, editable=False)),
                ('is_draft', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('addr_county', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.county')),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.category')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rank', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.rank')),
                ('source', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.source')),
                ('sponsor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.status')),
            ],
            options={
                'verbose_name': 'historical company',
                'verbose_name_plural': 'historical companys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, unique=True)),
                ('shortname', models.CharField(max_length=20, unique=True)),
                ('sn', models.CharField(max_length=9, unique=True)),
                ('stock_id', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('addr_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_title', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_tel', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True)),
                ('report', models.FileField(blank=True, null=True, upload_to='company/%Y/%m/')),
                ('pwr_usage', models.DecimalField(blank=True, decimal_places=1, max_digits=11, null=True)),
                ('pwr_inquire', models.DecimalField(blank=True, decimal_places=1, max_digits=11, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.IntegerField(default=0)),
                ('warn_date', models.DateField()),
                ('remark', models.CharField(blank=True, max_length=1000, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('addr_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company', to='core.county')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compauth', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company', to='core.category')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company', to='core.rank')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company', to='core.source')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compspnsr', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company', to='core.status')),
            ],
        ),
    ]
