# Generated by Django 4.0.5 on 2022-06-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_county_status_historicalsource_order_source_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='warn_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='warn_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
