# Generated by Django 4.0.5 on 2022-07-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_Change_Company_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
