"""
Django settings for retailCRM project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import ldap
from django_auth_ldap.config import LDAPSearch, GroupOfNamesType

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#j0vd8$bj2ql=i%edc023=8bf7bd25vj!@&^^n+np7@!7=!4c%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'salescall.apps.SalescallConfig',
    'simple_history',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'retailCRM.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'retailCRM' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'retailCRM.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'RetailCRM_UAT',
        'USER': 'ina-it',
        'PASSWORD': 'Pa$$w0rd_inaenergy',
        'HOST': '192.168.168.121',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            "extra_params": "TrustServerCertificate=yes",
        },
    },
    'SAT': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'INA_UAT': {
        'ENGINE': 'mssql',
        'NAME': 'RetailCRM_UAT',
        'USER': 'ina-it',
        'PASSWORD': 'Pa$$w0rd_inaenergy',
        'HOST': '192.168.168.121',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            "extra_params": "TrustServerCertificate=yes",
        },
    },
    'INA_Prod': {
        'ENGINE': 'mssql',
        'NAME': 'RetailCRM',
        'USER': 'ina-inner',
        'PASSWORD': '50791838@INAenergy',
        'HOST': '192.168.168.121',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'retailCRM/static_files/'

STATICFILES_DIRS = [BASE_DIR / 'retailCRM/static/']

MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / 'retailCRM/media_files/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 登入認證資料庫順序 1.LDAP 2.內建資料庫
AUTHENTICATION_BACKENDS = [
    "django_auth_ldap.backend.LDAPBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# ldap的連線基礎配置
AUTH_LDAP_SERVER_URI = "ldap://192.168.168.212:389"  # ldap or ad 伺服器地址
AUTH_LDAP_BIND_DN = "CN=SupplyChainAdmin,OU=Service Administrators,DC=inaenergy,DC=com,DC=tw"  # 管理員的dn路徑
AUTH_LDAP_BIND_PASSWORD = 'ina@50791838'  # 管理員密碼

# 允許認證使用者的路徑
AUTH_LDAP_USER_SEARCH = LDAPSearch("DC=inaenergy,DC=com,DC=tw",
                                   ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)")

# 通過組進行許可權控制
AUTH_LDAP_GROUP_SEARCH = LDAPSearch("OU=Group,DC=inaenergy,DC=com,DC=tw",
                                    ldap.SCOPE_SUBTREE, "(objectClass=top)")

AUTH_LDAP_GROUP_TYPE = GroupOfNamesType()


# 如果ldap伺服器是Windows的AD，需要配置上如下選項
AUTH_LDAP_CONNECTION_OPTIONS = {
    ldap.OPT_DEBUG_LEVEL: 1,
    ldap.OPT_REFERRALS: 0,
}

# 當ldap使用者登入時，從ldap的使用者屬性對應寫到django的user資料庫，鍵為django的屬性，值為ldap使用者的屬性
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}

# 如果為True，每次組成員都從ldap重新獲取，保證組成員的實時性；反之會對組成員進行快取，提升效能，但是降低實時性
AUTH_LDAP_FIND_GROUP_PERMS = True

# This is the default, but I like to be explicit.
AUTH_LDAP_ALWAYS_UPDATE_USER = True
# AUTH_LDAP_CACHE_GROUPS = True
# AUTH_LDAP_CACHE_TIMEOUT = 3600
AUTH_LDAP_MIRROR_GROUPS = True


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "loggers": {"django_auth_ldap": {"level": "DEBUG", "handlers": ["console"]}},
}

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
