# Generated by Django 4.0.5 on 2022-06-20 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_county_status_historicalsource_order_source_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=9)),
                ('calldate', models.DateField()),
                ('questions', models.CharField(max_length=1000)),
                ('requirement', models.CharField(max_length=1000)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='callrecord/%Y/%m/')),
                ('summary', models.CharField(max_length=200)),
                ('nextdate', models.DateField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='callrecords', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CallType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='salescall.callrecord')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCallRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sn', models.CharField(max_length=9)),
                ('calldate', models.DateField()),
                ('questions', models.CharField(max_length=1000)),
                ('requirement', models.CharField(max_length=1000)),
                ('attachment', models.TextField(blank=True, max_length=100, null=True)),
                ('summary', models.CharField(max_length=200)),
                ('nextdate', models.DateField()),
                ('add_time', models.DateTimeField(blank=True, editable=False)),
                ('update_time', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('auther', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('calltype', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='salescall.calltype')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical call record',
                'verbose_name_plural': 'historical call records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='calltype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='callrecords', to='salescall.calltype'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='callrecords', to='core.company'),
        ),
    ]
