# Generated by Django 4.0.5 on 2022-06-20 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salescall', '0001_create_salescall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callrecord',
            old_name='auther',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='historicalcallrecord',
            old_name='auther',
            new_name='author',
        ),
    ]
